# Generated by Django 5.0.1 on 2024-01-18 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_expense_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
